Repository Dawid64/decorify, pull requests merged in 2024-11, with the labels that each got.

#5 4 create general purpose decorators
  pydecorators/__init__.py
  pydecorators/basic.py
  tests/test_basic.py
Labels: enhancement

#10 3 create exception handling decorators
  pydecorators/__init__.py
  pydecorators/base_log.py
  pydecorators/exception_handler.py
  requirements.txt
  tests/test_exception_handler.py
Labels: documentation, enhancement

#16 Added New timeout decorator Solves #9
  decorify/__init__.py
  decorify/basic.py
  docs/source/index.rst
  tests/test_basic.py
Labels: enhancement

#27 Created code of conduct and simple contribution guide
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation
